site_name: Artificial Intelligence
site_url: https://lansky1.github.io/artificialintelligence/

nav:
  - Home: index.md
  - Generative AI: genai.md
  - MCP: mcp.md

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
